import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/query/QueryClientProvider";

export const metadata: Metadata = {
  title: "Ashyo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
